### PR TITLE
Basic landing page

### LINKED ISSUE #366: Landing page
Our current landing page is mostly just empty.

image

Isn't that quite a waste of space? Instead, we could use the space to give the user a better overview and make the search bar easier to find. Here is a quick sketch:

image

(What do you think, @TKGZ and @ningxie1991?)

### PR DESCRIPTION
**Pull request by spacephoton**
Can add more stuff later

CleanShot 2021-12-13 at 20 17 38@2x

#366

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Something is wrong with the scrolling. I can't move to the bottom of the page.

Landing page:


image

ExploreFocusSplit:

image

**Comment by spacephoton** [comment]
> Something is wrong with the scrolling. I can't move to the bottom of the page.
> 
> Landing page:
> 
> image
> 
> ExploreFocusSplit:
> 
> image

does it work for you now? this scroll stuff :)

**Comment by chaoran-chen** [comment]
The scroll in the ExploreFocusSplit works, but not on the landing page. Why does it work for you? o.O

image

**Comment by spacephoton** [comment]
What browser are you using？ Does it work now？ Had added the scroll configuring. Now I notice that 'h-full' added too much height to the explore page （which made unnecessary scroll) because it was returned from a function, and so it didn't take into account other components that were also on the page.  Removed both h-full and the scroll stuff, hope it works now 🤣

**Comment by spacephoton** [comment]
it's funny how sometimes you add CSS, then add more CSS to fix previous css, which creates more problems

**Comment by spacephoton** [comment]
spent too much time on this scroll stuff 🥲

**Comment by spacephoton** [comment]
Ah, I still get a double scrollbar :( 

Will have another look in the next days.

**Comment by chaoran-chen** [comment]
I think that's alright! The second scrollbar is due to the preview note.

I'll check it more closely later, but it looks good so far. Thanks for the quick and great work!! :)

**Review by chaoran-chen — APPROVED** [review]
Everything looks good to me! 👍 

I just added the footer.

@TKGZ Would you be interested to do #367 next?

**Comment by spacephoton** [comment]
> Everything looks good to me! 👍
> 
> I just added the footer.
> 
> @TKGZ Would you be interested to do #367 next?

we can discuss how to do this in next meeting :)

**Pull request merged**
