### PR TITLE
Add reproduction number estimates

### PR DESCRIPTION
**Pull request by chaoran-chen**
image

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@chaoran-chen it'd be cool if you could briefly describe purpose of a PR in the description so I and others know what's going on :) 

This is what I get, intriguing, though I have no idea what's going on.

image

**Comment by chaoran-chen** [comment]
It is marked as a draft (i.e., not ready for review, yet) ;)

But without any further information, what is your impression as a "naïve" user?

**Comment by corneliusroemer** [comment]
I'm wondering how many assumptions go into this and what is calculated.

How do you figure out the gen time? Is that an assumption or calculated within?

Is it a single number at a point in time, or changes over time? In which case it should be Rt or something like that in the title, I guess.

If it just says calculating it's hard to know what the output is gonna look like.

**Comment by chaoran-chen** [comment]
Yes, a (brief) model description is missing. The details are in the manuscript.

Did you get the result plot back?

**Pull request merged**
