### PR TITLE
feat: queue LAPIS calls on collection pages

### LINKED ISSUE #980: Improve collection performance
Improve CoV-Spectrum collection’s performance and support very large collections reliably.

E.g., https://cov-spectrum.org/collections/24 works in Firfox, but in Chrome the page crashes with "insufficient resources".

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #980 

The very large collection 24 (~1000 variants) will otherwise fail to load in Chrome with "net::ERR_INSUFFICIENT_RESOURCES"

With this fix, both collections successfully load in Chrome:
https://cov-spectrum-develop-git-980-improve-collec-dc213c-cov-spectrum.vercel.app/collections/127
https://cov-spectrum-develop-git-980-improve-collec-dc213c-cov-spectrum.vercel.app/collections/24

### CODE REVIEW

**Comment by chaoran-chen** [comment]
On my laptop, it indeed works now while it didn't work in the past - that's a great improvement (and definitely worth merging)! 

On my phone (Android + Chrome), it loads for half a minute and then shows a whitescreen unfortunately.

**Comment by fengelniederhammer** [comment]
On my mobile Chrome it successfully loaded. On the built-in Samsung browser, it did not.

**Review by JonasKellerer — APPROVED** [review]
LGTM

Maybe add a ticket to check this for mobile (samsung browser)

**Comment by fengelniederhammer** [comment]
I created #990 as a follow up

**Pull request merged**
