### PR TITLE
feat: adapt wastewater story text

### LINKED ISSUE #1014: Update text: Wastewater in Switzerland
The text of the page "Wastewater in Switzerland" needs to be updated as explained below. The changes have been reviewed by multiple members of the Beerenwinkel's group, including prof. Beerenwinkel.

```
Wastewater in Switzerland 

by [Computational Biology Group, ETH Zurich](https://bsse.ethz.ch/cbg/) 

We analyze wastewater samples collected at different Swiss wastewater treatment plants (see data sources below) using next-generation sequencing (done by [FGCZ](https://fgcz.ch/)), process the resulting short-read data with [V-pipe](https://cbg-ethz.github.io/V-pipe/), and search for mutations characteristic of variants of concern. The relative frequency of each signature mutation is determined, and all mutation frequencies are combined within a selected time window and translated into estimates of the relative prevalence of the variant in the population for each day. Some variants have specific signature mutations that co-occur on the same fragment. (see [doi:10.1101/2021.01.08.21249379](https://doi.org/10.1101/2021.01.08.21249379), [doi:10.1101/2022.11.02.22281825](https://doi.org/10.1101/2022.11.02.22281825) and [cowwid](https://github.com/cbg-ethz/cowwid) for more details). 

Detecting variants in wastewater is challenging if the RNA concentration is low, for example, due to low infection numbers in the catchment area of the wastewater treatment plant. Variants with very similar mutation profiles can also be harder to distinguish. Estimates of the proportions of variants are less reliable in these situations. 

 

[Current curves] 

Locations discontinued since March 26th 

[Discontinued curves] 

 

Data sources 

[Eawag](https://www.eawag.ch/en/department/sww/projects/sars-cov2-in-wastewater/) collects samples at multiple locations around Switzerland. Over the course of the project, different locations have been covered. Since March 26th of 2024 the following eight wastewater treatment plants are sampled three times per week: Altenrhein (SG), Chur (GR), Genève (GE), Laupen (BE), Lugano (TI), Zürich (ZH), Luzern (LU) and Basel (BS). 

Previously, the project covered six additional wastewater treatment plants: Lausanne (VD), Bern (BE), Porrentruy (JU), Neuchâtel (NE), Solothurn (SO), and Schwyz (SZ). 

Monitoring of Bern (BE) ended on March 25th, 2024. Monitoring of Lausanne ended February 24th, 2024. The monitoring of all other discontinued treatment plants ended on December 31st, 2023 

Previously, Microsynth AG provided samples from the wastewater treatment plants of Lausanne (Vidy), Sierre/Noes (VS) and Porrentruy (JU) (3 times per week until the beginning of July 2023). 

The Health Department of Basel-Stadt provided samples from the ProRheno AG wastewater treatment plant three times per week (once per week until the end of 2022). 

Until end of May 2022, three times a week the Cantonal Laboratory Zurich (KLZH) provided samples that assess the Canton of Zurich by pooling samples from 12 plants across the canton, namely Zürich-Werdhölzli (also used by Eawag), Winterthur-Hard, Dietikon-Limmattal, Dübendorf-Neugut, Niederglatt-Fischbach, Uster, Bülach-Furt, Wetzikon-Flos, Horgen-Oberrieden, Meilen, Affoltern a.A.-Zwillikon, and Illnau-Mannenberg. 

Data availability 

De-humanized sequencing libraries in FASTQ format for each collection event are publicly available on ENA under project ID [PRJEB44932](https://www.ebi.ac.uk/ena/browser/view/PRJEB44932). 

Video presentation of the surveillance project 

During the webinar ["Detecting COVID-19 Variants in Wastewater" by the International Water Association (IWA)](https://iwa-network.org/learn/detecting-covid-19-variants-in-wastewater/), Prof. Tamar Kohn, and Prof. Niko Beerenwinkel have presented this surveillance project. The presentation is the second session of this webinar,["Detection and surveillance of SARS-CoV-2 genomic variants in Swiss wastewater" (timecode 22:17).](https://vimeo.com/560055953#t=1337s). 

Acknowledgements 

[Computational Biology Group (CBG), ETH Zurich ](https://bsse.ethz.ch/cbg)/ [Swiss Institute of Bioinformatics](https://www.sib.swiss/niko-beerenwinkel-group) 

Ivan Topolsky, David Dreifuss, Anika John, Auguste Rimaite, Pelin Burcak Icer, Lara Fuhrmann, Niko Beerenwinkel 

[Computational Evolution (cEvo), ETH Zurich](https://bsse.ethz.ch/cevo) / [Swiss Institute of Bioinformatics](https://www.sib.swiss/tanja-stadler-group) 

Chaoran Chen, Sarah Nadeau, Tanja Stadler 

[NEXUS Personalized Health Technologies, ETH Zurich](https://www.nexus.ethz.ch/) / [Swiss Institute of Bioinformatics](https://www.sib.swiss/daniel-stekhoven-group) 

Matteo Carrara, Franziska Singer 

Eawag 

Tamar Kohn, Seju Kang, Ayazhan Dauletova, Camille Hablützel, Rachel McLeod, Daniela Yordanova, Jolinda de Korne, Charlie Gan, Lea Caduff, Christoph Ort, Timothy R. Julian 

Functional Genomic Center Zürich 

Catharine Aquino, Lennart Opitz, Tim Sykes 

Genomic Facility Basel 

Mirjam Feldkamp, Christian Beisel 

Laboratory of Environmental Chemistry EPFL 

Xavier Fernandez-Cassi, Federica Cariti, Alex Tuñas Corzón, Tamar Kohn 

Funding 

Federal Office for Public Health 

Contact 

Prof. Niko Beerenwinkel, [ETH](https://bsse.ethz.ch/cbg) Zurich.
```

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #1014

@mcarrara-bioinfo, you're welcome to check in the preview deployment whether the text looks as expected. Are the changes from "Zürich" to "Zurich" intentional?

### CODE REVIEW

**Comment by mcarrara-bioinfo** [comment]
Thank you for taking the time!
The points you raise are all correct:
- the line `Locations discontinued since March 26th` should include the date `2024`
- All instance of `Zurich` should instead be `Zürich`

Apart from that, everything looks perfect. After the changes I mentioned you can deploy the changes

**Comment by fengelniederhammer** [comment]
There are still two occurences of "Zurich" on the page:
`Until end of May 2022, three times a week the Cantonal Laboratory Zurich (KLZH) provided samples that assess the Canton of Zurich by pooling samples from 12 plants across the canton, [...]`.
I left them there as they seem correct to me and they have already been there before these changes.

**Comment by mcarrara-bioinfo** [comment]
Thank you very much

**Review by JonasKellerer — APPROVED** [review]
LGTM

**Pull request merged**
