### PR TITLE
WHO names

### LINKED ISSUE #181: WHO names
Use WHO names for key variants (such as Delta variant)
Goal: make it more accessible

- [ ] Preview
- [ ] Title in focus page
- [ ] Search

### PR DESCRIPTION
**Pull request by spacephoton**

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Hey. Looks good. Only one thing: Could we please write e.g. "B.1.1.7 (Alpha)" instead? I personally only need at the pangolin lineages and find it a little exhausting to have sometimes look at the first, and sometimes at the second word. Otherwise, good to merge!

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
Wait, does this PR contain #180? Please either split them or finish and merge #180 first ;)

**Comment by spacephoton** [comment]
Good point, I merged with the wrong branch. Will do 180 first then, and fix the names, thanks! :)

**Comment by spacephoton** [comment]
Although for the public, I think the other way around is easier, since most people don't know pangolin 👍

**Review by chaoran-chen — APPROVED** [review]
I like the style :)

**Pull request merged**
