### PR TITLE
CompareToBaseline and CompareEquals variant search field style

### PR DESCRIPTION
**Pull request by anastasia-escher**
Change styles for CompareToBaseline and CompareEquals variant search fields.

### CODE REVIEW

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
The mobile date range picker view took a hit. https://cov-spectrum-develop-git-comparetobaselinestyle-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.2.75*& looks like this:

image

The public version looks fine:

image

**Comment by anastasia-escher** [comment]
Hi, @chaoran-chen ! Strange, it looks ok on my phone. 
Which browser do you use? 
Screenshot_20220811-174456_Chrome

**Comment by anastasia-escher** [comment]
Ah, your screnshot is for a smaller screen than the one my phone has,  I didn't check it, sorry.

**Review by chaoran-chen — APPROVED** [review]
Thanks, this looks good! There is unfortunately now a conflict with the develop branch. Could you resolve it and then merge it, please?

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
Hi @anastasia-escher, I'm sorry but can I request one more change? I think that it is better to move the two small buttons (delete row and move up) to the left side. When I was using the search, I became aware that everything else is on the left side (add variant button, advanced search button, the known variant cards) and that I don't want to move my mouse all the way to the right. I am not sure if others think the same way but my feeling is that it is more comfortable if the buttons are closer together.

Screen Shot 2022-08-17 at 15 53 44

**Pull request closed without merging**
