### PR TITLE
Moved search bar to above the focus page on the right + use one scroll bar only

### LINKED ISSUE #367: Layout restructuring: move search bar and simplify ExplorePage
Here's an idea for a small restructuring. The search bar is on the right side. If we implement #366, the sequencing intensity plot is already on the landing page and does not need to appear on the ExploreFocusSplit-view. This allows us to make the left area narrower.

image

### PR DESCRIPTION
**Pull request by ningxie1991**
For #367 

image

### CODE REVIEW

**Comment by ningxie1991** [comment]
Some ideas to move the data range picker:

image

image

image

**Comment by chaoran-chen** [comment]
Maybe let it depend on the screen width?

**Comment by spacephoton** [comment]
what about the date range picker as part of the header?

**Comment by chaoran-chen** [comment]
Didn't we just move it out of the header a while ago? I remember two keys reasons: 1. the date picker does not apply to the preview plots on the left, 2. the header is already very crowded.

**Comment by ningxie1991** [comment]
Yes, those were the reasons. 

What do we think about these? I thought of a prettier way for the date range picker:

1.
image

2.
image


3. 
image


This react-bootstrap-daterangepicker can potentially contain the predefined ranges like this:

4.
image

5.
image

6.
image

7.
image

**Comment by chaoran-chen** [comment]
Both approaches look interesting! Could you maybe push them somewhere so that I can try them out in the preview?

**Comment by ningxie1991** [comment]
> Both approaches look interesting! Could you maybe push them somewhere so that I can try them out in the preview?

Option 1:
https://cov-spectrum-develop-4w0n2ereq-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*

**Comment by chaoran-chen** [comment]
I like the first option! Let's take it.

Could we have the preview plots a bit more narrow? I think that they can remain the same width as before and that we should give the additional space rather to the right side. The "Sequencing intensity" plot can be removed as it is already on the landing page.

**Pull request merged**
