### PR TITLE
get rid of warnings in console while executing the tests

### PR DESCRIPTION
**Pull request by fengelniederhammer**
The tests complained that the ExportManager was not set via the context provider.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Oh, sorry that it's not documented: these warnings shouldn't occur if you set the environment variable `REACT_APP_IS_TESTING=true`

**Comment by fengelniederhammer** [comment]
Why do we need an environment variable to control that? Doesn't it make more sense to test the components in a more realistic scenario, i.e. using the context providers? Then the tests could actually control the ExportManagers.

**Comment by chaoran-chen** [comment]
Good question. The disadvantage of this solution is that the charts will always be tested together with the ExportManager although they can be used alone.

I wonder whether a good solution might be to just remove the warnings ([code](https://github.com/GenSpectrum/cov-spectrum-website/blob/develop/src/components/CombinedExport/ExportManager.ts#L21)). I don't see big harm in calling `ExportManager.register()` even if there is no context provider - it's then just a no-op.

Ideally, I guess that the chart components should all be refactored to better separate the calculation logic, the view, and the DownloadWrapper (which calls the ExportManager). But that would take some effort

**Review by chaoran-chen — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
