### PR TITLE
Country selection

### LINKED ISSUE #459: Improve country selection
From the discussion in #321, I agree with @anastasia-escher that the current country selection in the top bar looks a bit unstructured. Maybe we can do something like this? We can then also add flags next to the country names.

image

### PR DESCRIPTION
**Pull request by anastasia-escher**
Reformatting the country select field with the material-ui library.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Hi @anastasia-escher! Thanks for the very quick work!

I will look into the code in more detail tomorrow or on Thursday, but already a few quick comments:

- You mixed the geographic granularity code from #458 into this PR. It would however be better to keep the branches separated and base off from the main branch for every PR. This would make the reviews much easier because right now, it's difficult for me to distinguish the code for the two features. Could you please resubmit the PR with only the code for the country selection (do you know how to do it with git?).
- It seems a bit too much to include a big UI library just for a small feature. If you could find a way to implement this without adding a (or four) new dependencies, it would be perfect. But if not, since we had been quite generous with adding new libraries so far, I guess that we can also accept a few more...
- Is this intended? It looks a bit weird to me that the field border does not go around the whole field, but I assume that this can also be interpreted as design.
image

**Comment by chaoran-chen** [comment]
Visually, it is now looking great! But the actual functionality (the country switching) is not working for me anymore. Is it working for you, @anastasia-escher?

**Comment by anastasia-escher** [comment]
It works differently, you have to change the country and click somewhere outside of the field (I had to use onBlur instead of onChange so that the value doesn't change with every typed letter but after the typing is done).

**Comment by chaoran-chen** [comment]
Ah! Could you maybe also implement switching by clicking the enter button?

**Comment by anastasia-escher** [comment]
Now it should switch directly by selecting.

**Comment by chaoran-chen** [comment]
Perfect!

I have two more ideas:

- Remove/reduce the left margin (red)
- Align the country names even if there is no flag available (blue)

image

**Review by chaoran-chen — APPROVED** [review]
Looks good to me! Thank you! Please merge if you think it's ready :)

**Pull request merged**
