### PR TITLE
Calculate Jaccard similarity as uniqueness score for mutations

### PR DESCRIPTION
**Pull request by chaoran-chen**
Many thanks to @adrian-lison for the discussion on uniqueness/similarity scores and for the suggestion to use Jaccard!

This feature helps us to find mutations that are unique to a variant.

Here's an example with B.1.1.7:

image

### CODE REVIEW

**Comment by corneliusroemer** [comment]
What's the Jaccard similarity calculated with respect to? All sequences in that timeframe in that country?

**Comment by corneliusroemer** [comment]
This is good! When I sort according to similarity, I get the new mutations that have arisen within AY.4.2 showing up, these are the mutations I'm tracking already, at least there's a good overlap, so this can be very helpful!
image

**Comment by corneliusroemer** [comment]
I love how the similarities pop up one after another async 👯 
image

**Comment by chaoran-chen** [comment]
It's calculating the similarity of the set of sequences belonging to the selected variant and the set of sequences belonging to the mutation. The country and date range filters apply as usual.

**Comment by corneliusroemer** [comment]
Right, so if a homoplasic mutation appears, like N501Y in AY.4.2, it would have a low Jaccard because N501Y has already popped up a lot in other sequences.
In that sense the mutations highlighted may actually be deleterious ones, since the ones giving an advantage will have already shown up frequently in the past.
It may be interesting to make the comparison with lineages one up in the hierarchy, for example AY.4 vs AY.4.2

**Comment by chaoran-chen** [comment]
> It may be interesting to make the comparison with lineages one up in the hierarchy, for example AY.4 vs AY.4.2

I can imagine that it will be eventually possible with #175. Then, you can select the variants that you would like to compare.

The hierarchy concept itself does not really fit cov-spectrum because a "variant" is often not (just) a pango lineage.

**Pull request merged**
