### PR TITLE
Bug/overflow fix

### LINKED ISSUE #316: Overflows on small screens
We have a number of components that overflow on smaller or mobile devices (probably mostly my fault!).

- [x] The buttons

image

- [x] Sequences over time chart

image

- [x] Transmission advantage chart

image

- [x] International comparison chart

image

### PR DESCRIPTION
**Pull request by gautier-collab**
Issue #403 : fixed the overflow issues on small screens.

That encompasses:
 - the position of "Export" and "Show regions" toolbar buttons
 - Sequences over time chart
 - Transmission advantage chart
 - International comparison chart

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Hm... The code format is still wrong. Is it possible that (somehow) you are having the wrong version of prettier? Or that you are calling it wrongly?

Edit: I think the problem is related to https://github.com/cevo-public/cov-spectrum-website/pull/404/files#r807217721

**Comment by gautier-collab** [comment]
I'm investigating why the test fails.

**Comment by chaoran-chen** [comment]
You need to update the snapshot tests. See: https://github.com/cevo-public/cov-spectrum-website/blob/develop/docs/tests.md#snapshot-tests

**Review by chaoran-chen — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
