### PR TITLE
When not using advanced search, first character entered for each term gets ignored.

### LINKED ISSUE #696: When not using advanced search, first character entered for each term gets ignored.
ie, if I want to search "s:486p, s:444t" I will have to type "ss:486p" enter, "ss:444t". Visually everything displays correctly, but the first button press doesn't make it in at all. 

I'm using google chrome, haven't tested on other browsers.

### PR DESCRIPTION
**Pull request by JonasKellerer**
Resolves: #696

### CODE REVIEW

**Review by chaoran-chen — APPROVED** [review]
Thank you! It works as far as I can tell!

Would you happen to know what triggered the bug? Why did it not occur in the past?

**Comment by chaoran-chen** [comment]
I merged it as it is an urgent bug fix.

**Comment by corneliusroemer** [comment]
Amazing, this works in my testing (tried out a number of edge cases as well!)

**Comment by fengelniederhammer** [comment]
> Would you happen to know what triggered the bug? Why did it not occur in the past?

We don't know for sure what caused the bug. We're pretty sure that it was introduced by the React 18 upgrade (on https://cov-spectrum-develop-git-fixwarnings-cov-spectrum.vercel.app/explore/Germany/AllSamples/Past6M it still works). 
We deleted that "if menu closed, then delete input" statement, because we found it quite weird and unintuitive anyway. That definitely caused the bug. So actually the question is, why did it work before at all? ;)

**Comment by FedeGueli** [comment]
great work thank you guys. we had already got used with that ;)

**Pull request merged**
