### PR TITLE
fix heatmap scroll

### LINKED ISSUE #195: Wastewater heatmap: Fix left column when scrolling
The left column with the mutation names of the wastewater heatmap should be fixed during horizontal scrolling if the width of the screen is large enough. 

image

### PR DESCRIPTION
**Pull request by spacephoton**
#195

When screen id bigger than tailwind `md`, keep left bar static, while the heatmap still scrollable horizontally.
CleanShot 2021-07-25 at 17 02 46@2x

### CODE REVIEW

**Comment by chaoran-chen** [comment]
It would be great if you could fix the code style so that we can use the Vercel preview :)

**Comment by chaoran-chen** [comment]
Hi @TKGZ. The labels are not aligned with the colored cells (in Chrome and Firefox on Windows). Do you (or @ningxie1991) have an idea how to fix it? Since the scrollbar has different heights in different browsers, I guess that this issue is not entirely trivial..

image

**Comment by spacephoton** [comment]
> Hi @TKGZ. The labels are not aligned with the colored cells (in Chrome and Firefox on Windows). Do you (or @ningxie1991) have an idea how to fix it? Since the scrollbar has different heights in different browsers, I guess that this issue is not entirely trivial..

Ah yes, this is a problem to fix

**Comment by spacephoton** [comment]
Yes, it depends on the browser. I added scrollbar on the left part too, can you have a look how it is now? On mac it's not a problem since it doesn't take space.

image

**Review by chaoran-chen — APPROVED** [review]
Lucky Mac :P

Now it works on Windows as well 👍 
image

**Comment by spacephoton** [comment]
> Lucky Mac :P
> 
> Now it works on Windows as well 👍
> image

not the most pretty but it works!

**Pull request merged**
